# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/seq2seq.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/seq2seq.proto\x12\x07seq2seq\"\x1f\n\rPromptRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"\x1e\n\x0bPromptReply\x12\x0f\n\x07message\x18\x01 \x01(\t2J\n\x07Seq2Seq\x12?\n\x0bPromptModel\x12\x16.seq2seq.PromptRequest\x1a\x14.seq2seq.PromptReply\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.seq2seq_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROMPTREQUEST._serialized_start=32
  _PROMPTREQUEST._serialized_end=63
  _PROMPTREPLY._serialized_start=65
  _PROMPTREPLY._serialized_end=95
  _SEQ2SEQ._serialized_start=97
  _SEQ2SEQ._serialized_end=171
# @@protoc_insertion_point(module_scope)
